// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmda0xIz7Mzm08RIZ5wiNBBaE6jzaJaNk',
    appId: '1:955133769342:web:457a15dea11ada1702ca2f',
    messagingSenderId: '955133769342',
    projectId: 'pinokio-play-app',
    authDomain: 'pinokio-play-app.firebaseapp.com',
    storageBucket: 'pinokio-play-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsxskCYweM20_zsw7lU1B39XFX54pXy4c',
    appId: '1:955133769342:android:1d6dd09370e45ab902ca2f',
    messagingSenderId: '955133769342',
    projectId: 'pinokio-play-app',
    storageBucket: 'pinokio-play-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7T5Q7DVZfGamVHsZwZmGTr4qIIFNz9IY',
    appId: '1:955133769342:ios:a55376d83313b44302ca2f',
    messagingSenderId: '955133769342',
    projectId: 'pinokio-play-app',
    storageBucket: 'pinokio-play-app.firebasestorage.app',
    iosBundleId: 'com.example.pinokioPlay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7T5Q7DVZfGamVHsZwZmGTr4qIIFNz9IY',
    appId: '1:955133769342:ios:a55376d83313b44302ca2f',
    messagingSenderId: '955133769342',
    projectId: 'pinokio-play-app',
    storageBucket: 'pinokio-play-app.firebasestorage.app',
    iosBundleId: 'com.example.pinokioPlay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmda0xIz7Mzm08RIZ5wiNBBaE6jzaJaNk',
    appId: '1:955133769342:web:19810b6fcbe5324202ca2f',
    messagingSenderId: '955133769342',
    projectId: 'pinokio-play-app',
    authDomain: 'pinokio-play-app.firebaseapp.com',
    storageBucket: 'pinokio-play-app.firebasestorage.app',
  );
}
